version: '3.7'

services:
  web1:
    build: ./services/web
    command: gunicorn --bind 0.0.0.0:5001 manage:app
    volumes:
      - ./services/web/:/usr/src/app/
    expose:
      - 5001
    env_file:
      - ./services/web/.env.dev
  

  web2:
    build: ./services/web
    command: gunicorn --bind 0.0.0.0:5002 manage:app
    volumes:
      - ./services/web/:/usr/src/app/
    expose:
      - 5002
    env_file:
      - ./services/web/.env.dev

  web3:
    build: ./services/web
    command: gunicorn --bind 0.0.0.0:5003 manage:app
    volumes:
      - ./services/web/:/usr/src/app/
    expose:
      - 5003
    env_file:
      - ./services/web/.env.dev

#take
  nginx:
    build: ./services/nginx
    ports:
      - 1337:80
    depends_on:
      - web1
      - web2
      - web3



      # web3:
      #   build: ./services/web
      #   command: gunicorn --bind 0.0.0.0:5003 manage:app
      #   volumes:
      #     - ./services/web/:/usr/src/app/
      #   expose:
      #     - 5003
      #   env_file:
      #     - ./services/web/.env.dev